### ISSUE TITLE
git init is enough

### ISSUE THREAD

**Issue by Namek** [zelazowy/git_practice#2]
Let's learn then!

You don't have to make a repo and clone it. Just `git init` in any folder. Later, optionally - `git remote add origin <git_url>` to enable pushing it.

Have a nice day 👊

**Comment by zelazowy** [comment]
Oh, I should definitely check more often github notifications...
Thanks for comment - I'll try it way next time 👍

**Comment by zelazowy** [comment]
Hmm, but still, I need to create repo on GitHub, right? So there are two ways to create repo and do something there:
1. create repo -> git clone -> do something -> git push
2. create repo -> do something -> git remote add -> git push

Am I right? :)

**Comment by Namek** [comment]
yup
